apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  instances: {{ .Values.instances }}
  # PDB: CloudNativePG operator creates a PDB by default (enablePDB: true); for 3 instances only one pod is disrupted at a time.
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: {{ .Values.externalSecrets.superuser.secretName }}
  storage:
    size: {{ .Values.storageSize }}
    {{- if .Values.storageClass }}
    storageClass: {{ .Values.storageClass }}
    {{- end }}
  # Soft affinity: prefer nodes with label node-role=database (homelab convention).
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node-role
                operator: In
                values:
                  - database
